// landing-page/src/components/Navbar.vue
<script setup>
import { ref, computed } from "vue";
import { useRoute } from "vue-router";
import { AlignJustify, X, Bell } from "lucide-vue-next";

const isMenuOpen = ref(false);
const route = useRoute();

const navItems = [
  { id: "home", name: "Home", path: "/" },
  { id: "about", name: "About", path: "/about" },
  { id: "features", name: "Features", path: "/features" },
  { id: "security", name: "Security", path: "/security" },
  { id: "contacts", name: "Contacts", path: "/contacts" },
];

const toggleMenu = () => {
  isMenuOpen.value = !isMenuOpen.value;
};

const isActive = (path) => {
  return route.path === path;
};
</script>

<template>
  <!-- Mobile Menu Toggle Button -->
  <div class="border border-red-500">
    <div>
      <p>BeanCart</p>
    </div>
    <div>
      <div>
        <Bell />
      </div>
    <button @click="toggleMenu" class="md:hidden  z-40">
      <AlignJustify v-if="!isMenuOpen" />
    </button>
  </div>
  </div>

  <!-- Black Overlay -->
  <Transition name="overlay">
    <div class="absolute bg-black/50 inset-0 z-20" @click="toggleMenu" v-if="isMenuOpen"></div>
  </Transition>
  <!-- Mobile Navigation Menu -->
  <Transition name="sidebar">
    <div v-if="isMenuOpen" class="md:hidden fixed inset-0 z-30">

      <!-- Sidebar container -->
      <div class="bg-indigo-100 w-[70%] h-screen absolute right-0 top-0 z-30 pt-16 px-5 overflow-hidden">
        <Transition name="title-animation" appear>
          <div class="absolute top-2 font-bold text-2xl text-indigo-400">
            <h2>BeanCart</h2>
          </div>
        </Transition>
        <div class="absolute top-2 right-2" @click="toggleMenu">
          <X class="w-8 h-7 text-indigo-300" />
        </div>

        <div class="h-[250px] w-[250px] bg-indigo-200 rounded-full absolute -top-[125px] -left-[150px] -z-10"></div>

        <TransitionGroup name="list" tag="ul" class="w-full" appear>
          <li v-for="(item, index) in navItems" :key="item.id" :style="{ '--stagger-delay': `${index * 0.1}s` }">
            <router-link :to="item.path"
              class="flex px-4 py-3 w-full mt-5 rounded-sm shadow-sm font-semibold text-lg text-gray-500" :class="isActive(item.path) ? 'bg-indigo-300' : 'bg-indigo-300/30'
                " @click="toggleMenu">
              {{ item.name }}
            </router-link>
          </li>
        </TransitionGroup>

        <Transition name="slide-fade" appear>
          <button class="absolute bottom-24 px-4 py-3 bg-indigo-400 rounded-sm w-[80%] text-center shadow-md">
            <p class="font-semibold text-xl text-white">Get Started</p>
          </button>
        </Transition>

        <div class="absolute h-[700px] w-[700px] bg-indigo-200 rounded-full -z-10 -bottom-[200px] -left-[50px]"></div>
        <div class="bg-indigo-300 h-[100px] w-[100px] rounded-full absolute bottom-[200px]"></div>
        <div class="bg-indigo-300 h-[50px] w-[50px] rounded-full absolute bottom-[200px] right-[50px]"></div>
        <div class="bg-indigo-300 h-[40px] w-[40px] rounded-full absolute bottom-[300px] right-[25px]"></div>
      </div>
    </div>
  </Transition>

  <!-- Desktop Navigation -->
  <nav class="hidden md:flex justify-center py-4 bg-indigo-50">
    <ul class="flex space-x-6">
      <li v-for="item in navItems" :key="item.id">
        <router-link :to="item.path" class="px-4 py-2 rounded-md font-medium transition-colors" :class="isActive(item.path)
          ? 'bg-indigo-300 text-indigo-900'
          : 'hover:bg-indigo-200'
          ">
          {{ item.name }}
        </router-link>
      </li>
    </ul>
  </nav>

  <!-- Content Area -->
  <router-view />
</template>

<style>
/* Sidebar Animation */
.sidebar-enter-active,
.sidebar-leave-active {
  transition: transform 0.4s ease, opacity 0.4s ease;
}

.sidebar-enter-from {
  transform: translateX(100%);
  opacity: 0;
}

.sidebar-enter-to {
  transform: translateX(0%);
  opacity: 1;
}

.sidebar-leave-from {
  transform: translateX(0%);
  opacity: 1;
}

.sidebar-leave-to {
  transform: translateX(100%);
  opacity: 0;
}

/* Overlay Fade Animation */
.overlay-enter-active,
.overlay-leave-active {
  transition: opacity 0.1s ease;
}

.overlay-enter-from,
.overlay-leave-to {
  opacity: 0;
}

.overlay-enter-to,
.overlay-leave-from {
  opacity: 0.5;
}

.list-enter-active {
  transition: all 0.5s ease;
  transition-delay: var(--stagger-delay, 0s);
}

.list-enter-from,
.list-leave-to {
  opacity: 0;
  transform: translateX(30px);
}

/* Title animations */
.title-animation-enter-active,
.title-animation-leave-active {
  transition: all 0.4s ease-in;
}

.title-animation-enter-from,
.title-animation-leave-to {
  opacity: 0;
  transform: translateX(20px);
}

/* Button animations */
.slide-fade-enter-active,
.slide-fade-leave-active {
  transition: all 0.4s ease-in;
}

.slide-fade-enter-from,
.slide-fade-leave-to {
  opacity: 0;
  transform: translateY(20px);
}
</style>

// frontend/src/app/core/layout/navbar/navbar.component.ts
// src/app/core/layout/navbar/navbar.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { RouterLink, Router, NavigationEnd } from '@angular/router';
import { NgClass, NgIf, CommonModule } from '@angular/common';
import { filter } from 'rxjs/operators';
import { AuthStateService } from '../../auth/auth-state.service';
import { Subscription } from 'rxjs';

// Import LucideAngularModule and the specific icons
import { LucideAngularModule } from 'lucide-angular';
import { Menu, X, User } from 'lucide-angular';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterLink, NgIf, CommonModule, LucideAngularModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit, OnDestroy {
  // Define icon references
  readonly menuIcon = Menu;
  readonly closeIcon = X;
  readonly userIcon = User;

  isMenuOpen = false;
  activeRoute: string = '';
  isLoggedIn = false;
  userProfile: any = null;
  private authSubscription!: Subscription;

  get menuItems() {
    const guestMenuItems = [
      { path: '/', name: 'Home' },
      { path: '/products', name: 'Products' },
      { path: '/cart', name: 'Cart' },
      { path: '/user/login', name: 'Login' },
      { path: '/user/register', name: 'Register' },
    ];
    
    const authenticatedMenuItems = [
      { path: '/', name: 'Home' },
      { path: '/products', name: 'Products' },
      { path: '/cart', name: 'Cart' },
      { path: '/user/profile', name: 'Profile' },
      { path: '/user/orders', name: 'Orders' },
    ];
    
    return this.isLoggedIn ? authenticatedMenuItems : guestMenuItems;
  }
    
  constructor(
    private router: Router,
    private authStateService: AuthStateService
  ) {
    this.router.events.pipe(
      filter(event => event instanceof NavigationEnd)
    ).subscribe((event: any) => {
      this.activeRoute = event.url;
    });
  }
    
  ngOnInit() {
    this.authSubscription = this.authStateService.currentUser$.subscribe(user => {
      this.isLoggedIn = !!user;
      this.userProfile = user;
    });
  }
    
  ngOnDestroy() {
    if (this.authSubscription) {
      this.authSubscription.unsubscribe();
    }
  }
    
  toggleMenu() {
    this.isMenuOpen = !this.isMenuOpen;
  }
    
  logout() {
    this.authStateService.logout();
    this.router.navigate(['/']);
  }
    
  isActive(route: string): boolean {
    return this.activeRoute === route;
  }
}
<!-- src/app/core/layout/navbar/navbar.component.html -->
<!-- Desktop Navbar (Indigo Background) -->
<nav class="hidden md:flex justify-between items-center py-4 px-6 bg-indigo-600 text-white relative z-20">
  <div class="flex items-center">
    <a routerLink="/" class="text-xl font-bold">BeanCart</a>
  </div>
  
  <div class="flex items-center space-x-6">
    @for (item of menuItems; track item.path) {
      <a [routerLink]="item.path" 
         [class.font-bold]="isActive(item.path)" 
         class="hover:text-indigo-200 transition"
         [ngClass]="{'underline': isActive(item.path)}">
        {{item.name}}
      </a>
    }
    
    @if (isLoggedIn) {
      <div class="relative group">
        <div class="flex items-center cursor-pointer">
          @if (userProfile?.profileImageUrl) {
            <img [src]="userProfile.profileImageUrl" 
                 alt="Profile" 
                 class="w-8 h-8 rounded-full object-cover border-2 border-indigo-200" />
          } @else {
            <span class="w-8 h-8 rounded-full bg-indigo-200 flex items-center justify-center">
              <lucide-angular [img]="userIcon" size="16" class="text-indigo-600"></lucide-angular>
            </span>
          }
        </div>
        
        <!-- Dropdown Menu (Indigo Theme) -->
        <div class="absolute right-0 mt-2 w-48 bg-white shadow-lg rounded-md overflow-hidden z-10 hidden group-hover:block border border-indigo-100">
          <div class="px-4 py-2 border-b bg-indigo-50">
            <p class="font-medium text-indigo-800">{{ userProfile?.firstName || 'User' }} {{ userProfile?.lastName || '' }}</p>
            <p class="text-indigo-600 text-xs">{{ userProfile?.email }}</p>
          </div>
          <a routerLink="/user/profile" class="block px-4 py-2 hover:bg-indigo-50 text-sm text-indigo-700">View Profile</a>
          <a routerLink="/user/orders" class="block px-4 py-2 hover:bg-indigo-50 text-sm text-indigo-700">My Orders</a>
          <button (click)="logout()" class="w-full text-left px-4 py-2 hover:bg-indigo-50 text-sm text-red-600">Logout</button>
        </div>
      </div>
    }
  </div>
</nav>

<!-- Mobile Navbar (Indigo Background) -->
<nav class="md:hidden flex justify-between items-center py-4 px-4 bg-indigo-600 text-white">
  <a routerLink="/" class="text-xl font-bold">BeanCart</a>
  
  <div class="flex items-center">
    @if (isLoggedIn) {
      <div class="mr-4">
        @if (userProfile?.profileImageUrl) {
          <img [src]="userProfile.profileImageUrl" 
               alt="Profile" 
               class="w-8 h-8 rounded-full object-cover border-2 border-indigo-200" />
        } @else {
          <span class="w-8 h-8 rounded-full bg-indigo-200 flex items-center justify-center">
            <lucide-angular [img]="userIcon" size="16" class="text-indigo-600"></lucide-angular>
          </span>
        }
      </div>
    }
    
    <button (click)="toggleMenu()" class="p-1 text-white">
      @if (isMenuOpen) {
        <lucide-angular [img]="closeIcon" size="24"></lucide-angular>
      } @else {
        <lucide-angular [img]="menuIcon" size="24"></lucide-angular>
      }
    </button>
  </div>
</nav>

<!-- Mobile Menu Overlay -->
<div *ngIf="isMenuOpen" class="fixed inset-0 bg-black bg-opacity-50 z-40 md:hidden" (click)="toggleMenu()"></div>

<!-- Mobile Menu (Indigo Theme) -->
<div *ngIf="isMenuOpen" class="fixed right-0 top-0 bottom-0 w-64 bg-white z-50 shadow-lg transform transition-transform md:hidden">
  <div class="flex justify-between items-center p-4 border-b bg-indigo-600 text-white">
    <h2 class="font-bold">Menu</h2>
    <button (click)="toggleMenu()" class="p-1">
      <lucide-angular [img]="closeIcon" size="24"></lucide-angular>
    </button>
  </div>
  
  <div class="p-4">
    @if (isLoggedIn) {
      <div class="flex items-center mb-6 pb-4 border-b border-indigo-100">
        @if (userProfile?.profileImageUrl) {
          <img [src]="userProfile.profileImageUrl" 
               alt="Profile" 
               class="w-10 h-10 rounded-full object-cover mr-3 border-2 border-indigo-200" />
        } @else {
          <span class="w-10 h-10 rounded-full bg-indigo-200 flex items-center justify-center mr-3">
            <lucide-angular [img]="userIcon" size="20" class="text-indigo-600"></lucide-angular>
          </span>
        }
        <div>
          <p class="font-medium text-indigo-800">{{ userProfile?.firstName || 'User' }} {{ userProfile?.lastName || '' }}</p>
          <p class="text-indigo-600 text-sm">{{ userProfile?.email }}</p>
        </div>
      </div>
    }
    
    <ul class="space-y-4">
      @for (item of menuItems; track item.path) {
        <li>
          <a [routerLink]="item.path" 
             [class.font-bold]="isActive(item.path)"
             class="block py-2 px-2 rounded hover:bg-indigo-50 text-indigo-700 transition"
             [ngClass]="{'bg-indigo-100 text-indigo-800': isActive(item.path)}"
             (click)="toggleMenu()">
            {{item.name}}
          </a>
        </li>
      }
      
      @if (isLoggedIn) {
        <li class="border-t border-indigo-100 pt-2 mt-4">
          <button (click)="logout(); toggleMenu()" 
                  class="w-full text-left py-2 px-2 text-red-600 hover:bg-red-50 rounded transition">
            Logout
          </button>
        </li>
      }
    </ul>
  </div>
</div>
